<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tero
 * Date: Fri, 27 Mar 2020 09:56:33 +0000
 */

$conf['title'] = 'River2River';
$conf['start'] = 'home';
$conf['sidebar'] = 'menubar';
$conf['license'] = '0';
$conf['hidepages'] = '^:(admin*|menubar|playground|labels|templates|waiting-for-approval)';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['passcrypt'] = 'pmd5';
$conf['superuser'] = '@admin';
$conf['manager'] = '@mods';
$conf['plugin']['approve']['no_apr_namespaces'] = 'user menubar cookies privacy-policy home faq media forum el:home waiting-for-approval';
$conf['plugin']['translation']['translations'] = 'el,sq';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['checkage'] = 1;
$conf['plugin']['translation']['copytrans'] = 1;
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['useavatar'] = 0;
$conf['plugin']['discussion']['subscribe'] = 0;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['discussion']['moderate'] = 1;
$conf['plugin']['discussion']['moderatorgroups'] = '@mods';
$conf['plugin']['discussion']['moderatorsnotify'] = 1;

// end auto-generated content
